package com.example.develop_api.entity;

import lombok.Data;
import jakarta.persistence.*;

@Data
@Entity
@Table(name = "roles")
public class Role {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String name;

    // Constructors, getters, and setters can be generated by Lombok's @Data annotation

    public Role() {
    }

    public Role(String name) {
        this.name = name;
    }

}
