package com.example.develop_api.payload;

import lombok.Data;

@Data
public class LoginDto {

    private String username;
    private String password;

    // Constructors, getters, setters can be generated by Lombok's @Data annotation

    public LoginDto() {
    }

    public LoginDto(String username, String password) {
        this.username = username;
        this.password = password;
    }
}
