package com.example.develop_api.payload;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.time.LocalDate;

@Data
public class SignUpDto {

    private String name;
    private String username;
    private String email;
    private String password;
    private String confirmPassword; // Used to confirm that the password is correctly entered
    private LocalDate birthday;
    private String course;
    private Integer age;

    // Constructors, getters, setters can be generated by Lombok's @Data annotation

    public SignUpDto() {
    }

    public SignUpDto(String name, String username, String email, String password, String confirmPassword, LocalDate birthday, String course, Integer age) {
        this.name = name;
        this.username = username;
        this.email = email;
        this.password = password;
        this.confirmPassword = confirmPassword;
        this.birthday = birthday;
        this.course = course;
        this.age = age;
    }
}
